;;; easy-kill-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from easy-kill.el

(autoload 'easy-kill "easy-kill" "\
Kill thing at point in the order of region, url, email and line.
Temporally activate additional key bindings as follows:

  letters => select or expand selection according to `easy-kill-alist';
  1..9    => expand selection by that number;
  0       => shrink to the initial selection;
  +,=/-   => expand or shrink selection;
  @       => append selection to previous kill;
  ?       => help;
  C-w     => kill selection;
  SPC     => cycle through things in `easy-kill-alist';
  C-SPC   => turn selection into an active region;
  C-g     => abort;
  others  => save selection and exit.

(fn &optional N)" t)
(defalias 'easy-mark-sexp #'easy-mark "\
Use `easy-mark' instead. The alias may be removed in future.")
(autoload 'easy-mark "easy-kill" "\
Similar to `easy-kill' (which see) but for marking.

(fn &optional N)" t)
(autoload 'easy-dup "easy-kill" "\
Insert a copy of the current selection after it, or before it if BEFORE.
When not in easy-kill/easy-mark, enter `easy-mark' mode using the active
region if available, or using `easy-dup-try-things' to select something
to duplicate.  When in `rectangle-mark-mode', duplicate the rectangle
region and keep the mode active without entering `easy-mark'.

N specifies the number of copies to insert.

(fn &optional N BEFORE)" t)
(defalias 'easy-dup-after #'easy-dup)
(autoload 'easy-dup-before "easy-kill" "\
Insert a copy of the current selection before it.
When not in easy-kill/easy-mark, enter `easy-mark' mode using the active
region if available, or using `easy-dup-try-things' to select something
to duplicate.  When in `rectangle-mark-mode', duplicate the rectangle
region and keep the mode active without entering `easy-mark'.

N specifies the number of copies to insert.

(fn &optional N)" t)
(register-definition-prefixes "easy-kill" '("easy-"))

;;; End of scraped data

(provide 'easy-kill-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; easy-kill-autoloads.el ends here
